# Generated by Django 5.1.7 on 2025-03-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_movies_usermovie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='movies',
        ),
    ]
