# Generated by Django 5.1.7 on 2025-03-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_movies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermovie',
            options={'verbose_name': 'Фильм пользователя', 'verbose_name_plural': 'Фильмы пользователя'},
        ),
        migrations.AddField(
            model_name='usermovie',
            name='mark',
            field=models.IntegerField(blank=True, choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], null=True, verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='usermovie',
            name='review',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='usermovie',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время добавления'),
        ),
    ]
