# Generated by Django 5.1.7 on 2025-04-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_date_to_pay_user_type_of_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_of_sub',
            field=models.CharField(choices=[('FREE', 'FREE'), ('STANDARD', 'STANDARD'), ('PREMIUM', 'PREMIUM')], default='FREE', max_length=8, verbose_name='Тип подписки'),
        ),
    ]
